### ISSUE TITLE
desired commit granularity & wording?

### ISSUE THREAD

**Issue by jgpawletko** [jgpawletko/git_transactor#1]
cc: @eshadatta 

@barnabyalter,  I don't know the internals of your Jenkins re-index job,  so I need your input on the following questions:

## Commit Granularity

**Option 1: commit after each requested change**
e.g., 
```
git add archives/diner.xml
git commit -m "......"
git rm tamwag/oh2.xml
git commit -m "......"
git add fales/champagne.xml
git commit -m "......"
```  

**Option 2: commit after all requested changes**
```
git add archives/diner.xml
git rm tamwag/oh2.xml
git add fales/champagne.xml
git commit -m "......"
```

## Commit Message wording
Based on your chosen option above, how do you want the commit messages to read?  

In [Esha's story](https://www.pivotaltracker.com/story/show/67329732) the acceptance criteria specifies:
`Must have a commit message "Updating file <FILENAME>"`
but I don't see a corresponding requirement for the [delete case](https://www.pivotaltracker.com/story/show/67337958). I propose using `Deleting file <FILENAME>`.

Therefore, **Commit Granularity Option 1** would look like this:
```
git add archives/diner.xml
git commit -m "Updating file archives/diner.xml"
git rm tamwag/oh2.xml
git commit -m "Deleting file tamwag/oh2.xml"
git add fales/champagne.xml
git commit -m "Updating file fales/champagne.xml"
```  
And, **Commit Granularity Option 2** could look like this:
```
git add archives/diner.xml
git rm tamwag/oh2.xml
git add fales/champagne.xml
git commit -m "Updating file archives/diner.xml, Deleting file tamwag/oh2.xml, Updating file fales/champagne.xml"
```  

Please let me know your preferences or propose alternate solutions.

Thanks for your time!
Joe

**Comment by barnabyalter** [comment]
@jgpawletko These are very good questions and they uncover a problem with my script: I was under the initial assumption that every time a change was made there would be a commit and a push. And so the comparison only looks at the previous commit: https://github.com/NYULibraries/findingaids/blob/development/lib/findingaids/ead/indexer.rb#L43

Several commits followed by a push will only reindex the changes from the very last commit. Obviously a problem with keeping things in sync. **So let's say we have to use #2**.

**Comment by jgpawletko** [comment]
@barnabyalter 
Thanks! option 2 it is.
